# Generated by Django 4.2.20 on 2025-04-20 17:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=10, verbose_name='Tipo de Descuento'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Valor del descuento (porcentaje o monto fijo)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Descuento'),
        ),
    ]
