# Generated by Django 4.2.20 on 2025-04-20 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0002_coupon_discount_type_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Usado por'),
        ),
    ]
