# Generated by Django 4.2.20 on 2025-04-20 23:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_coupon_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a usuario específico'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Cupón exclusivo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(help_text='Porcentaje de descuento (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)'),
        ),
    ]
