# Generated by Django 4.2.20 on 2025-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, null=True),
        ),
    ]
