# Generated by Django 4.2.20 on 2025-04-27 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        # Se eliminaron las operaciones RemoveField porque los campos ya no existen en el modelo Profile
        # o ya fueron eliminados en migraciones anteriores
        # Se eliminó la creación del modelo Address porque la tabla ya existe en la base de datos
    ]
