# Generated by Django 4.2.20 on 2025-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_address_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Información Adicional'),
        ),
        migrations.AddField(
            model_name='address',
            name='department',
            field=models.CharField(default='Lima', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='Lima', max_length=100, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='Lima', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='address',
            name='recipient',
            field=models.CharField(default='', max_length=100, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Calle/Avenida'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.CharField(default='', max_length=50, verbose_name='Número/Lote/Dpto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Perú', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Dirección Predeterminada'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
    ]