# Generated by Django 4.2.20 on 2025-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_create_address_model'),
    ]
    operations = []