# Generated by Django 4.2.20 on 2025-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250427_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Casa'), ('work', 'Trabajo'), ('other', 'Otro')], default='home', max_length=10),
        ),
    ]