# Generated by Django 4.2.20 on 2025-04-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_update_address_model'),
        ('users', '0008_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
    ]
