# Generated by Django 4.2.20 on 2025-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20250429_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('home', 'Casa'), ('work', 'Trabajo'), ('other', 'Otro')], default='home', max_length=10, null=True, verbose_name='Tipo de dirección'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Perú', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Destinatario'),
        ),
    ]
