# Generated by Django 4.2.20 on 2025-04-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('cart', '0002_cart_coupon_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
