# Generated by Django 4.2.20 on 2025-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_coupon_alter_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
