# Generated by Django 4.2.20 on 2025-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_discount_type_alter_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
