# Generated by Django 4.2.20 on 2026-07-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_discount_type_alter_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'variant'], name='cart_cartit_cart_id_bddf3b_idx'),
        ),
    ]
