# Generated by Django 5.1.5 on 2025-03-23 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_correlativo', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carnet de Extranjería'), ('pasaporte', 'Pasaporte')], max_length=15)),
                ('numero_documento', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('representante', models.CharField(blank=True, help_text='Padre o Madre / Representante (en el caso que usted sea menor de edad)', max_length=100, null=True)),
                ('tipo_solicitud', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10)),
                ('nombre_pedido', models.CharField(max_length=100)),
                ('monto_reclamado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_reclamo', models.CharField(choices=[('reclamo', 'Reclamo (disconformidad relacionada a los productos o servicios)'), ('queja', 'Queja (disconformidad no relacionada a los productos o servicios; o, malestar o descontento respecto a la atención al público)')], default='reclamo', max_length=10)),
                ('detalle', models.TextField()),
                ('pedido', models.TextField()),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones y acciones adoptadas por el proveedor', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reclamación',
                'verbose_name_plural': 'Reclamaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
