# Generated by Django 5.1.5 on 2025-03-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacion',
            old_name='nombre_pedido',
            new_name='numero_pedido',
        ),
    ]
