"""Django settings for ecommercesite project.
Generated by 'django-admin startproject' using Django 5.1.5.

Este archivo está obsoleto. Por favor, use 'ecommercesite.settings.development' o
'ecommercesite.settings.production' en su lugar.
"""
import os
import sys
import warnings
from pathlib import Path
from decouple import config

# Mostrar advertencia de que este archivo está obsoleto
warnings.warn(
    "Este archivo settings.py está obsoleto. "
    "Por favor, use 'ecommercesite.settings.development' o 'ecommercesite.settings.production' en su lugar.",
    DeprecationWarning
)

# Redirigir a la configuración de desarrollo por defecto
from .settings.development import *

